name: cognizelabcore
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pip
  - pip:
      - nilearn
      - nibabel
      - nipype
      - -e ./python
